### ISSUE TITLE
Link for data on research page

### ISSUE THREAD

**Issue by wavingtowaves** [ddimmery/quarto-website#1]
Hi @ddimmery! Thanks so much for sharing your website code--it's great and so helpful. 👍🏻 

I've been using it to build my own quarto website. I particularly like how you've set up your research page.  I wonder how difficult it would be to add in a new type of link on the research page (in addition to, published paper, preprint, and github) for something like "data" in case there is any data associated with the manuscript that's stored in a repository and not on github alone?  I haven't dug into too much of the code on research.qmd, but I imagine that would be how we could start to create this new button? Thanks!

**Comment by ddimmery** [comment]
Hi Rob, glad it could be useful. To add in other kinds of buttons, it's relatively straightforward:

1. Add lines to the [YAML](https://github.com/ddimmery/quarto-website/blob/main/papers.yaml) for each publication called `data` or something.
2. Choose an icon to use on the research page (e.g. from Bootstrap Icons). For example, [bi-file-earmark-bar-graph](https://icons.getbootstrap.com/icons/file-earmark-bar-graph/)
3. Add lines in `research.qmd` like the `github` field (order of the `buttons` list matters for ordering the links, so keep that in mind):
```
data = data.get("data")
if data is not None:
    buttons.append(button(data, "Github", "bi-file-earmark-bar-graph"))
```

Right now I don't personally need this functionality (so I'm closing as wont-fix), but it should be easy enough to fork and modify to your taste!
